(define (problem kitten_q3-problem)
 (:domain kitten_q3-domain)
 (:objects
   kitten0 kitten1 kitten2 kitten3 kitten4 - kitten
 )
 (:init
              (connected kitchen playroom)
              (connected playroom kitchen)
              (toy_free)
              (current_room kitten0 playroom)
              (current_room kitten1 kitchen)
              (current_room kitten2 playroom)
              (current_room kitten3 kitchen)
              (current_room kitten4 playroom)
 )
 (:goal (and 
           (has_drunk kitten0)
           (has_played kitten0)
           (has_drunk kitten1)
           (has_played kitten1)
           (has_drunk kitten2)
           (has_played kitten2)
           (has_drunk kitten3)
           (has_played kitten3)
           (has_drunk kitten4)
           (has_played kitten4)
        )
 )
)
